title: <p align="center"> Faiqi Nabil </p>

logo: "/images/Pas-Red Circle Square (Jas Edit).png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="hhttps://www.linkedin.com/in/faiqinabil/</a> |
  <a href="https://github.com/Faiqeh">GitHub</a>
  </p>
  
  <p align="justify">
  I am an undergraduate student of Information Systems at Universitas Negeri Semarang.
  <br><br>
  I am interested in website development, data science & analytics, and network engineering.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
